/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CenteredDiv: typeof import('./src/components/CenteredDiv.vue')['default']
    DivOverlay: typeof import('./src/components/DivOverlay.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ModalProvider: typeof import('./src/components/ModalProvider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
