/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AspectContainer: typeof import('./src/components/AspectContainer.vue')['default']
    CenteredDiv: typeof import('./src/components/CenteredDiv.vue')['default']
    DivOverlay: typeof import('./src/components/DivOverlay.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InfiniteScroller: typeof import('./src/components/InfiniteScroller.vue')['default']
    ModalProvider: typeof import('./src/components/ModalProvider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shrinker: typeof import('./src/components/shrinker/Shrinker.vue')['default']
    ShrinkerConfig: typeof import('./src/components/shrinker/ShrinkerConfig.vue')['default']
    ShrinkerPlay: typeof import('./src/components/shrinker/ShrinkerPlay.vue')['default']
    ShrinkerResults: typeof import('./src/components/shrinker/ShrinkerResults.vue')['default']
    ShrinkerWelcome: typeof import('./src/components/shrinker/ShrinkerWelcome.vue')['default']
    SpotifyTrack: typeof import('./src/components/SpotifyTrack.vue')['default']
    SpotifyTrackTile: typeof import('./src/components/SpotifyTrackTile.vue')['default']
    StartOverlay: typeof import('./src/components/StartOverlay.vue')['default']
  }
}
